### ISSUE TITLE
Content Strategy for the Handbook

### ISSUE THREAD

**Issue by richardswain** [humanmade/hmn-handbook#19]
Reasoning:
To enable a better user experience (i.e. avoid #nipgate), improve navigation & structure, expand content.
Enable a future public release.

Inspiration:
https://www.gov.uk/service-manual
https://10up.github.io/Engineering-Best-Practices/

Any input about the current handbook good and bad, from current users is welcome..

**Comment by rmccue** [comment]
I've started on this independently of the handbook with the [developer resources](https://hmn.hackpad.com/collection/EHxWlxhgV9b) Hackpads. I think it makes sense to keep this separate to the handbook, so that the Handbook is essentially our day-to-day ops, and the Engineering Resources site for how we build things.

Contributions and thoughts on the Hackpads welcome too :)

**Comment by willmot** [comment]
@richardswain given this repo is public I think we should probably keep it just for theme improvements and talk about the content somewhere else (a hackpad, P2 post etc).
