### ISSUE TITLE
Style Home Page

### ISSUE THREAD

**Issue by scottbasgaard** [humanmade/hmn-handbook#20]
See:
- https://handbook.hmn.md/

Remove UL disc styling.

**Comment by richardswain** [comment]
Not sure whats happened to this (something reverted?)

https://github.com/humanmade/hmn-handbook/pull/6

**Comment by richardswain** [comment]
@willmot I have an issue with the List category posts widget on local with notices. Could this stop the live rendering correctly? i don't get the same styling locally as on live.

`PHP Notice:  The called constructor method for WP_Widget is <strong>deprecated</strong> since version 4.3.0! Use <pre>__construct()</pre> instead. in /srv/www/hmn.dev/wordpress/wp-includes/functions.php on line 3456`

I can rewrite the constructor to remove the notices - but was wondering if this could cause the live issue?

**Comment by willmot** [comment]
@richardswain I'm assuming live is also a caching issue?

**Comment by willmot** [comment]
But yep, we should also fix the notice

**Comment by richardswain** [comment]
No longer an issue.
